// !!! This is a file automatically generated by hipify!!!
#pragma once

#include <ATen/Tensor.h>
#include "graph_hip.cuh"

void hgemm_gr
(
    at::Tensor a,
    at::Tensor b,
    at::Tensor c,
    Graph* graph
);

void hgemm
(
    at::Tensor a,
    at::Tensor b,
    at::Tensor c
);