// !!! This is a file automatically generated by hipify!!!
#include "cuda_host.h"
#include <ATen/hip/HIPContext.h>
#include "util.h"

void cuda_host_register(uintptr_t ptr, size_t nbytes, unsigned int flags)
{
    hipError_t cr = hipHostRegister(reinterpret_cast<void*>(ptr), nbytes, flags);

    // A region can only be pinned once per process, but ranks sharing an arena may each try to
    // register it. The runtime also records the returned error as the last error, so clear it or
    // the next hipGetLastError() elsewhere (torch's launch checks) attributes it to something
    // unrelated
    if (cr == hipErrorHostMemoryAlreadyRegistered)
    {
        hipGetLastError();
        return;
    }

    TORCH_CHECK(
        cr == hipSuccess,
        "hipHostRegister(", reinterpret_cast<void*>(ptr), ", ", nbytes, ") failed: ",
        hipGetErrorString(cr)
    );
}

void cuda_host_unregister(uintptr_t ptr)
{
    hipError_t cr = hipHostUnregister(reinterpret_cast<void*>(ptr));

    // Teardown is racy by nature: the region may already have been released, or the runtime may
    // be unloading while shared segments are still being torn down. Both are benign here
    if (cr == hipErrorHostMemoryNotRegistered || cr == hipErrorDeinitialized)
    {
        hipGetLastError();
        return;
    }

    TORCH_CHECK(
        cr == hipSuccess,
        "hipHostUnregister(", reinterpret_cast<void*>(ptr), ") failed: ", hipGetErrorString(cr)
    );
}

uintptr_t cuda_host_get_device_pointer(uintptr_t ptr)
{
    // Device-side alias of memory registered with hipHostRegisterMapped. Equal to the host
    // pointer under UVA (Linux desktop), but distinct under WDDM (native Windows, and potentially
    // WSL2), where the host pointer is not usable in kernels and this alias must be passed instead
    void* dev_ptr = nullptr;
    hipError_t cr = hipHostGetDevicePointer(&dev_ptr, reinterpret_cast<void*>(ptr), 0);

    TORCH_CHECK(
        cr == hipSuccess,
        "hipHostGetDevicePointer(", reinterpret_cast<void*>(ptr), ") failed: ",
        hipGetErrorString(cr)
    );

    return reinterpret_cast<uintptr_t>(dev_ptr);
}

int cuda_device_get_attribute(int attr, int device)
{
    int value = 0;
    hipError_t cr = hipDeviceGetAttribute(&value, static_cast<hipDeviceAttribute_t>(attr), device);

    TORCH_CHECK(
        cr == hipSuccess,
        "hipDeviceGetAttribute(", attr, ", ", device, ") failed: ", hipGetErrorString(cr)
    );

    return value;
}
