// !!! This is a file automatically generated by hipify!!!
#include "cuda_host.h"
#include <ATen/ATen.h>
#include <ATen/hip/HIPContext.h>
#include "util.h"

void cuda_host_register(uintptr_t ptr, size_t nbytes, unsigned int flags)
{
    hipError_t cr = hipHostRegister(reinterpret_cast<void*>(ptr), nbytes, flags);

    // A region can only be pinned once per process, but ranks sharing an arena may each try to
    // register it. The runtime also records the returned error as the last error, so clear it or
    // the next hipGetLastError() elsewhere (torch's launch checks) attributes it to something
    // unrelated
    if (cr == hipErrorHostMemoryAlreadyRegistered)
    {
        hipGetLastError();
        return;
    }

    TORCH_CHECK(
        cr == hipSuccess,
        "hipHostRegister(", reinterpret_cast<void*>(ptr), ", ", nbytes, ") failed: ",
        hipGetErrorString(cr)
    );
}

void cuda_host_unregister(uintptr_t ptr)
{
    hipError_t cr = hipHostUnregister(reinterpret_cast<void*>(ptr));

    // Teardown is racy by nature: the region may already have been released, or the runtime may
    // be unloading while shared segments are still being torn down. Both are benign here
    if (cr == hipErrorHostMemoryNotRegistered || cr == hipErrorDeinitialized)
    {
        hipGetLastError();
        return;
    }

    TORCH_CHECK(
        cr == hipSuccess,
        "hipHostUnregister(", reinterpret_cast<void*>(ptr), ") failed: ", hipGetErrorString(cr)
    );
}

uintptr_t cuda_host_get_device_pointer(uintptr_t ptr)
{
    // Device-side alias of memory registered with hipHostRegisterMapped. Equal to the host
    // pointer under UVA (Linux desktop), but distinct under WDDM (native Windows, and potentially
    // WSL2), where the host pointer is not usable in kernels and this alias must be passed instead
    void* dev_ptr = nullptr;
    hipError_t cr = hipHostGetDevicePointer(&dev_ptr, reinterpret_cast<void*>(ptr), 0);

    TORCH_CHECK(
        cr == hipSuccess,
        "hipHostGetDevicePointer(", reinterpret_cast<void*>(ptr), ") failed: ",
        hipGetErrorString(cr)
    );

    return reinterpret_cast<uintptr_t>(dev_ptr);
}

int cuda_device_get_attribute(int attr, int device)
{
    int value = 0;
    hipError_t cr = hipDeviceGetAttribute(&value, static_cast<hipDeviceAttribute_t>(attr), device);

    TORCH_CHECK(
        cr == hipSuccess,
        "hipDeviceGetAttribute(", attr, ", ", device, ") failed: ", hipGetErrorString(cr)
    );

    return value;
}

at::Tensor pinned_cuda_view(const at::Tensor& t, int64_t device)
{
    // CUDA-device alias of a pinned host tensor: same storage, but with a device dtype/layout
    // so torch ops (matmul/cuBLAS) and extension kernels accept it directly, reading over PCIe
    // (zero-copy). The view does NOT own the memory; the caller must keep the pinned source
    // tensor alive for the alias's lifetime. Uses hipHostGetDevicePointer rather than assuming
    // UVA pointer equality so the alias also holds under WDDM
    TORCH_CHECK(t.device().is_cpu(), "pinned_cuda_view: tensor must be a CPU tensor");
    TORCH_CHECK(t.is_pinned(), "pinned_cuda_view: tensor must be pinned");
    void* dev_ptr = nullptr;
    hipError_t cr = hipHostGetDevicePointer(&dev_ptr, t.data_ptr(), 0);
    TORCH_CHECK(
        cr == hipSuccess,
        "hipHostGetDevicePointer(", t.data_ptr(), ") failed: ", hipGetErrorString(cr)
    );
    auto options = t.options().device(at::kCUDA, static_cast<c10::DeviceIndex>(device));
    return at::from_blob(dev_ptr, t.sizes(), t.strides(), [](void*) {}, options);
}
