// !!! This is a file automatically generated by hipify!!!
#pragma once

#include <hip/hip_runtime.h>

void inplace_bf16_to_fp16_cpu
(
    void* buffer,
    const size_t numel
);

hipError_t inplace_bf16_to_fp16_cuda
(
    void* buffer,
    const size_t numel,
    hipStream_t stream
);
